from service.network import Network
import requests
import time

def lampadaStatus(idLampada, status):
        Network.atualizaStatus(idLampada, status)

def main():
    while True:
        time.sleep(1)
        lampadaStatus(1, True)
        time.sleep(1)
        lampadaStatus(1, False)
        time.sleep(2)
        lampadaStatus(1, True)
        time.sleep(2)
        lampadaStatus(1, False)
        time.sleep(3)
        lampadaStatus(1, True)
        time.sleep(3)
        lampadaStatus(1, False)
        time.sleep(4)
        lampadaStatus(1, True)
        time.sleep(4)
        lampadaStatus(1, False)
        time.sleep(5)
        lampadaStatus(1, True)
        time.sleep(5)
        lampadaStatus(1, False)
        time.sleep(6)
        lampadaStatus(1, True)
        time.sleep(6)
        lampadaStatus(1, False)
        time.sleep(7)
        lampadaStatus(1, True)
        time.sleep(7)
        lampadaStatus(1, False)
        time.sleep(8)
        lampadaStatus(1, True)
        time.sleep(8)
        lampadaStatus(1, False)
        time.sleep(9)
        lampadaStatus(1, True)
        time.sleep(9)
        lampadaStatus(1, False)
        time.sleep(10)
        lampadaStatus(1, True)
        time.sleep(10)
        lampadaStatus(1, False)
        pass
main()